### ISSUE TITLE
[企業] 新增成員 Admin 按鈕不好按

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/planXcape-internal-feedback#3]
![2019-02-20 5 47 06](https://user-images.githubusercontent.com/2792565/53082336-9cb39900-3537-11e9-9966-3cd23b8e5a52.png)
現在要點按鈕左邊才可以開關

**Comment by ppuff1988** [comment]
操作邏輯有誤，應該是按右邊按鈕滑到右邊（現在是按左邊滑到右邊）

**Comment by jjjj4564** [comment]
> ![2019-02-20 5 47 06](https://user-images.githubusercontent.com/2792565/53082336-9cb39900-3537-11e9-9966-3cd23b8e5a52.png)
> 現在要點按鈕左邊才可以開關

改好摟

**Comment by jjjj4564** [comment]
> 操作邏輯有誤，應該是按右邊按鈕滑到右邊（現在是按左邊滑到右邊）

這個元件只有簡單的toggle而已 跟按左邊按右邊沒關係

**Comment by jjjj4564** [comment]
> 另外預設沒有onchange 就不會塞值進來，因此會變成子會員時權限為 null
