### ISSUE TITLE
[錯字]

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/planXcape-internal-feedback#6]
![2019-02-20 6 01 49](https://user-images.githubusercontent.com/2792565/53083349-afc76880-3539-11e9-9f69-b9b0cdf25c88.png)
![2019-02-20 6 01 53](https://user-images.githubusercontent.com/2792565/53083350-afc76880-3539-11e9-84bc-5b89768d72e6.png)

**Comment by littlegreening** [comment]
昨天改好了
